### PR TITLE
Creating a latest version with available docs

### PR DESCRIPTION
**Pull request by CirKu17**
I added a _latest_ release with available documents from https://github.com/OWASP/DevSecOpsGuideline .

The version is linked from the existing main page and accessible at _/latest_. It is built following the conventions I found on other OWASP repositories (namely WSTG).

I did not edit the text of documents themselves.

### CODE REVIEW

**Comment by Ali-Yazdani** [comment]
Hi @CirKu17, 
What is your comment about doing the same as MSTG? and Keep this repo just to introduce the project and manage release on the content repo?

**Comment by CirKu17** [comment]
Hi @Ali-Yazdani ,
I referred to WSTG because I adopted the same file and directory structure.
For what I understand this repo builds to https://owasp.org/www-project-devsecops-guideline/ so I think it should contain the latest available content for the project website.
While the other repo holds content and downloadable releases. Is this right?

**Comment by Ali-Yazdani** [comment]
Dear @CirKu17 , 
I agree with you, please update the PR.

**Comment by CirKu17** [comment]
Hi @Ali-Yazdani , I fetched upstream, please double check if everything's correct since quite some time passed from my last commit!

**Comment by Ali-Yazdani** [comment]
Hi @CirKu17, 
Somethings wrong, please check

**Pull request merged**
